TchotchoLoto/Models/Ticket.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.GagnantLotteries = new HashSet<GagnantLotterie>();
            this.TicketDetails = new HashSet<TicketDetail>();
        }
    
        public int TicketId { get; set; }
        public string CodeTicket { get; set; }
        public int UserPointDeVenteId { get; set; }
        public Nullable<int> TirageId { get; set; }
        public bool IsGagnant { get; set; }
        public bool IsDjapot { get; set; }
        public System.DateTime DateCreation { get; set; }
        public bool IsVente { get; set; }
        public Nullable<System.DateTime> DateVente { get; set; }
        public string BouleListes { get; set; }
        public Nullable<System.DateTime> DateTirage { get; set; }
        public string NomJoueur { get; set; }
        public string JacpotBoule { get; set; }
        public Nullable<int> Prix { get; set; }
        public Nullable<int> Tour { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GagnantLotterie> GagnantLotteries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
        public virtual Tirage Tirage { get; set; }
        public virtual UserPointDeVente UserPointDeVente { get; set; }
    }
}

TchotchoLoto/Controllers/TicketsController.cs
using TchotchoLoto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Diagnostics;

namespace TchotchoLoto.Controllers
{
    public class TicketsController : Controller
    {
        // GET: Tickets
        Entities db = new Entities();

        [AjaxOnly]
        public ActionResult Index()
        {

            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];


            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }




            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "Tickets/Index", "Bouton All Ticket [Ticket]");



            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }


            if (currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "tickets" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {

                List<StatutEntite> currentStatutPointDeVente = (List<StatutEntite>)Session["statutEntiteData"];
                if (currentStatutPointDeVente != null && currentStatutPointDeVente.Count() > 0)
                {
                    ViewBag.StatutId = new SelectList(currentStatutPointDeVente, "Id", "Description");
                }
                else
                {
                    currentStatutPointDeVente.Insert(0, new StatutEntite { Description = "All Status", Id = -1 });
                    currentStatutPointDeVente.Insert(1, new StatutEntite { Description = "Active", Id = 1 });
                    currentStatutPointDeVente.Insert(2, new StatutEntite { Description = "Inactive", Id = 0 });

                    ViewBag.StatutId = new SelectList(currentStatutPointDeVente, "Id", "Description");

                }

                var userPointDeVentes = db.UserPointDeVentes.OrderBy(o => o.User.LastName).AsEnumerable().Select(s => new { s.UserPointDeVenteId, NomComplet = s.User.FirstName + " " + s.User.LastName + " / " + s.PointDeVente.NomPointDeVente }).ToList();
                ViewBag.UserPointDeVenteId = new SelectList(userPointDeVentes, "UserPointDeVenteId", "NomComplet");


                ViewBag.Tickets = db.Tickets.Where(t => t.Tirage.LotterieTirages.Count() == 0).ToList();

                return View();
            }
            else
            {
                return Json(new { noPermission = true }, JsonRequestBehavior.AllowGet);
            }

        }






        [AjaxOnly]
        public ActionResult __Index(int? id)
        {

            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];


            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }

            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "Tickets/Index", "Bouton Select Statut Ticket / New Ticket => Save [Ticket]");


            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();


            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }

            if (currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "tickets" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {


                string message = null;

                List<StatutEntite> currentStatutPointDeVente = (List<StatutEntite>)Session["statutEntiteData"];
                if (currentStatutPointDeVente != null && currentStatutPointDeVente.Count() > 0)
                {
                    ViewBag.StatutId = new SelectList(currentStatutPointDeVente, "Id", "Description");
                }
                else
                {
                    currentStatutPointDeVente.Insert(0, new StatutEntite { Description = "All Status", Id = -1 });
                    currentStatutPointDeVente.Insert(1, new StatutEntite { Description = "Active", Id = 1 });
                    currentStatutPointDeVente.Insert(2, new StatutEntite { Description = "Inactive", Id = 0 });

                    ViewBag.StatutId = new SelectList(currentStatutPointDeVente, "Id", "Description");

                }

                if (id == null)
                {
                    message = "Please Select Status!";
                    return Json(new { notFound = true, message }, JsonRequestBehavior.AllowGet);

                }

                var tickets = new List<Ticket>();

                if (id == 0)
                {
                    tickets = db.Tickets.Where(t => !t.IsVente && t.Tirage.LotterieTirages.Count() == 0).ToList();

                }
                else if (id == 1)
                {

                    tickets = db.Tickets.Where(t => t.IsVente && t.Tirage.LotterieTirages.Count() == 0).ToList();

                }
                else
                {
                    tickets = db.Tickets.Where(t => t.Tirage.LotterieTirages.Count() == 0).ToList();

                }

                ViewBag.Tickets = tickets;


                var userPointDeVentes = db.UserPointDeVentes.OrderBy(o => o.User.LastName).AsEnumerable().Select(s => new { s.UserPointDeVenteId, NomComplet = s.User.FirstName + " " + s.User.LastName + " / " + s.PointDeVente.NomPointDeVente }).ToList();
                ViewBag.UserPointDeVenteId = new SelectList(userPointDeVentes, "UserPointDeVenteId", "NomComplet");




                return PartialView();

            }
            else
            {
                return Json(new { noPermission = true }, JsonRequestBehavior.AllowGet);
            }

        }







        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _Index([Bind(Include = "TicketId, UserPointDeVenteId")] Ticket ticket, int quantite)
        {
            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];


            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);

            }


            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "Tickets/_Index", "Bouton New Ticket => Save [Ticket]");



            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }


            if (currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "tickets" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {
                string message = null;


                if (ticket.UserPointDeVenteId > 0)
                {

                    UserPointDeVente userPointDeVenteExist = db.UserPointDeVentes.FirstOrDefault(u => u.UserId == ticket.UserPointDeVenteId);


                    if (userPointDeVenteExist == null)
                    {
                        message = "User not exist in point of sale!";
                        return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                    }


                    using (var dbContextTransaction = db.Database.BeginTransaction())
                    {

                        int enreg = 0;
                        int echou = 0;
                        int qtTotal = quantite;



                        if (ticket.TicketId == 0 && quantite <= 0)
                        {
                            message = "Please enter the ticket Quantity !";
                            return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);
                        }


                        if (ticket.TicketId != 0)
                        {

                            Ticket ticketEdit = db.Tickets.FirstOrDefault(t => t.TicketId == ticket.TicketId);


                            if (ticketEdit == null)
                            {
                                message = "Ticket not exist!";
                                return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                            }


                            if (ticketEdit.IsVente || ticketEdit.Prix.HasValue)
                            {
                                message = "This Ticket is already sold. You can not edit it!";
                                return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);
                            }

                            ticketEdit.UserPointDeVenteId = ticket.UserPointDeVenteId;



                            ticketEdit.ModifiePar = currentUser.FirstName + " " + currentUser.LastName;

TchotchoLoto/Views/Tickets/AllPendingTicket.cshtml
@model TchotchoLoto.Models.Ticket

@{
    ViewBag.Title = "Ticket";
    Layout = null;
}

<input type="hidden" class="title" data-title="Sale of Ticket" />

<div class="indicator" id="noPrintTicket">
    Ticket  &nbsp;&nbsp; <span class="glyphicon glyphicon-chevron-right"></span> &nbsp; &nbsp; All pending Ticket

</div>

<div class="indicator" id="printTicket" style="display:none;">
    Ticket <span class="glyphicon glyphicon-chevron-right"></span>  <a href="@Url.Action( "AllPendingTicket", "Tickets")" class="sub-view-back-to-parent-link" style="text-decoration:none; text-decoration-style: none;" title="Click to return to All Pending Ticket">All Pending Ticket</a>  <span class="glyphicon glyphicon-chevron-right"></span>print
</div>




<div class="header-body">
    <p style="display:inline-block;">
        Ticket (<span id="hb-nbre-ticket-vendeur">
            @if (ViewBag.PendingTickets != null)
            {@ViewBag.PendingTickets.Count}
        else { Write(0); }
        </span>)
        &nbsp;&nbsp;<span class="glyphicon star glyphicon-star text-success"></span>
    </p>


</div>

<br />



<div class="page-scroll-content" id="ticket-vendeur-list-pv">

    @Html.Partial("__AllPendingTicket")

</div>

<input id="url-get-ticket-vendeur-Printer-list" type="hidden" data-url="@Url.Action("__AllPendingTicket", "Tickets")" />






<div id="edit-boule-in-ticket-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

    </div>
</div>





<div id="ticket-info-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

        <!-- Modal content-->
    </div>
</div>




<div id="ticket-boule-info-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

        <!-- Modal content-->
    </div>
</div>


<!-- Modal 2 Dialog for delete option -->
<div id="delete-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Deletion</h4>

                <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>

            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-alert" style="display:block; font-size: 20px;"></span>
                <h5 class="text-warning" style="display:block;">Do you really want to Delete this Ticket ?</h5>

            </div>

            <div class="modal-footer">

                <a class="delete-confirmed btn btn-sm btn-danger" href="#">
                    YES
                </a>

                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">
                    NO
                </button>

            </div>
        </div>

    </div>
</div>



<a id="validation-link" data-toggle="modal" data-target="#modal-dialog-message"></a>

<div id="modal-dialog-message" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Message</h4>

            </div>
            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-info-sign" style="display:block; font-size: 20px;"></span>
                <h5 class="text-info" style="display:block;">@ViewBag.message</h5>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">
                    OK
                </button>
            </div>
        </div>

    </div>
</div>


<div id="pv-overlay-loading" class="overlay-loading bc-overlay-loading" style="display:none;">
    <img src="~/Content/images/loading-gif.gif" alt="Loading" width="50" height="50" />
</div>

TchotchoLoto/Views/Tickets/AllTicketVendeurHistories.cshtml
@model TchotchoLoto.Models.Ticket
@{
    ViewBag.Title = "Ticket Histories";
    Layout = null;
}



<input type="hidden" class="title" data-title="Ticket Histories" />

<div class="indicator">
    Ticket &nbsp;&nbsp; <span class="glyphicon glyphicon-chevron-right"></span>  &nbsp; &nbsp; Ticket Histories
</div>


<div class="header-body">

    <p style="display:inline-block;" class="qt-dataTable">
        &nbsp;&nbsp; Draw List(<span id="hb-nbre-allTicketHistories">
            @if (ViewBag.AllTicketHistories != null)
            {@ViewBag.AllTicketHistories.Count}
        else { Write(0); }
        </span>)
        &nbsp;<span class="glyphicon star glyphicon-star text-success"></span>

        @using (Html.BeginForm("__AllTicketVendeurHistories", "Tickets", FormMethod.Get, htmlAttributes: new { id = "allTicketHistories-list-form" }))
        {

            <div class="form-group col-md-3 col-sm-4 col-xs-4" title="Begin Date" style="padding-left:1px; width: 200px;">
                <input type="date" name="dateDebut" id="dateDebut" class="form-control" style="border: 1px solid #31b0d5; background: #31b0d5; color:white;">
            </div>

            <div class="form-group col-md-3 col-sm-4 col-xs-4" title="End Date" style="margin-left:-25px; width: 200px;">
                <input type="date" name="dateFin" id="dateFin" class="form-control" style="border: 1px solid #31b0d5; background: #31b0d5; color:white;">
            </div>
            <div class="form-group col-md-2 col-sm-2 col-xs-2" style="margin-left:-25px;">
                <button style="margin-right:10px; background: #31b0d5; color: dimgrey; border: none; color:white;" class="btn btn-md  submit" title="Search for this Date">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </div>
        }
    </p>



</div>

<br />




<div class="page-scroll-content" id="allTicketHistories-list-pv">

    @Html.Partial("__AllTicketHistories")

</div>






<div id="ticket-info-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

        <!-- Modal content-->
    </div>
</div>


<a id="validation-link" data-toggle="modal" data-target="#modal-dialog-message"></a>

<div id="modal-dialog-message" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Message</h4>

            </div>
            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-info-sign" style="display:block; font-size: 20px;"></span>
                <h5 class="text-info" style="display:block;">@ViewBag.message</h5>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">
                    OK
                </button>
            </div>
        </div>

    </div>
</div>

TchotchoLoto/Views/Tickets/IndexTicketBouleVendeurs.cshtml
@model TchotchoLoto.Models.Ticket

@{
    ViewBag.Title = "Ticket";
    Layout = null;
}

<input type="hidden" class="title" data-title="Ticket" />


<div class="indicator" id="noPrintTicket">
    Ticket  &nbsp;&nbsp; <span class="glyphicon glyphicon-chevron-right"></span> &nbsp; &nbsp; Sale Ticket

</div>

<div class="indicator" id="printTicket" style="display:none;">
    List <span class="glyphicon glyphicon-chevron-right"></span>  <a href="@Url.Action( "IndexTicketBouleVendeurs", "Tickets")" class="sub-view-back-to-parent-link" style="text-decoration:none; text-decoration-style: none;" title="Click to return to All Pending Ticket">Sale Ticket</a>  <span class="glyphicon glyphicon-chevron-right"></span>print
</div>


<div class="header-body">
    <p style="display:inline-block;">
        Ticket (<span id="hb-nbre-ticket-vendeur">
            @if (ViewBag.TicketVendeurs != null)
            {@ViewBag.TicketVendeurs.Count}
        else { Write(0); }
        </span>)
        &nbsp;&nbsp;<span class="glyphicon star glyphicon-star text-success"></span>
    </p>



</div>

<br />



<div class="page-scroll-content" id="ticket-vendeur-list-pv">

    @Html.Partial("__IndexTicketBouleVendeurs")

</div>

<input id="url-get-ticket-vendeur-Printer-list" type="hidden" data-url="@Url.Action("__IndexVendeurPrinter", "Tickets")" />







<div id="edit-boule-in-ticket-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

    </div>
</div>





<div id="ticket-info-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

        <!-- Modal content-->
    </div>
</div>




<div id="ticket-boule-info-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

        <!-- Modal content-->
    </div>
</div>


<!-- Modal 2 Dialog for delete option -->
<div id="delete-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Deletion</h4>

                <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>

            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-alert" style="display:block; font-size: 20px;"></span>
                <h5 class="text-warning" style="display:block;">Do you really want to Delete this Ticket ?</h5>

            </div>

            <div class="modal-footer">

                <a class="delete-confirmed btn btn-sm btn-danger" href="#">
                    YES
                </a>

                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">
                    NO
                </button>

            </div>
        </div>

    </div>
</div>



<a id="validation-link" data-toggle="modal" data-target="#modal-dialog-message"></a>

<div id="modal-dialog-message" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Message</h4>

            </div>
            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-info-sign" style="display:block; font-size: 20px;"></span>
                <h5 class="text-info" style="display:block;">@ViewBag.message</h5>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">
                    OK
                </button>
            </div>
        </div>

    </div>
</div>


<div id="pv-overlay-loading" class="overlay-loading bc-overlay-loading" style="display:none;">
    <img src="~/Content/images/loading-gif.gif" alt="Loading" width="50" height="50" />
</div>

TchotchoLoto/Views/Tickets/PendingTicketVendeur.cshtml
@model TchotchoLoto.Models.Ticket

@{
    ViewBag.Title = "Ticket";
    Layout = null;
}

<input type="hidden" class="title" data-title="Sale of Ticket" />

<div class="indicator" id="noPrintTicket">
    Ticket  &nbsp;&nbsp; <span class="glyphicon glyphicon-chevron-right"></span> &nbsp; &nbsp; Pending Ticket

</div>

<div class="indicator" id="printTicket" style="display:none;">
    Ticket <span class="glyphicon glyphicon-chevron-right"></span>  <a href="@Url.Action( "PendingTicketVendeur", "Tickets")" class="sub-view-back-to-parent-link" style="text-decoration:none; text-decoration-style: none;" title="Click to return to Pending Ticket"> Pending Ticket</a>  <span class="glyphicon glyphicon-chevron-right"></span>print
</div>




<div class="header-body">
    <p style="display:inline-block;">
        Ticket (<span id="hb-nbre-ticket-vendeur">
            @if (ViewBag.TicketVendeurs != null)
            {@ViewBag.TicketVendeurs.Count}
        else { Write(0); }
        </span>)
        &nbsp;&nbsp;<span class="glyphicon star glyphicon-star text-success"></span>
    </p>


</div>

<br />



<div class="page-scroll-content" id="ticket-vendeur-list-pv">

    @Html.Partial("__PendingTicketVendeur")

</div> 

<input id="url-get-ticket-vendeur-Printer-list" type="hidden" data-url="@Url.Action("__PendingTicketVendeur", "Tickets")" />






<div id="edit-boule-in-ticket-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

    </div>
</div>





<div id="ticket-info-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

        <!-- Modal content-->
    </div>
</div>




<div id="ticket-boule-info-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-md">

        <!-- Modal content-->
    </div>
</div>


<!-- Modal 2 Dialog for delete option -->
<div id="delete-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Deletion</h4>

                <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>

            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-alert" style="display:block; font-size: 20px;"></span>
                <h5 class="text-warning" style="display:block;">Do you really want to Delete this Ticket ?</h5>

            </div>

            <div class="modal-footer">

                <a class="delete-confirmed btn btn-sm btn-danger" href="#">
                    YES
                </a>

                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">
                    NO
                </button>

            </div>
        </div>

    </div>
</div>



<a id="validation-link" data-toggle="modal" data-target="#modal-dialog-message"></a>

<div id="modal-dialog-message" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Message</h4>

            </div>
            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-info-sign" style="display:block; font-size: 20px;"></span>
                <h5 class="text-info" style="display:block;">@ViewBag.message</h5>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">
                    OK
                </button>
            </div>
        </div>

    </div>
</div>


<div id="pv-overlay-loading" class="overlay-loading bc-overlay-loading" style="display:none;">
    <img src="~/Content/images/loading-gif.gif" alt="Loading" width="50" height="50" />
</div>

TchotchoLoto/Views/Tickets/_Edit.cshtml
@model TchotchoLoto.Models.Ticket

<div class="modal-content">
    <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

        <h4 style="display: inline;">Edit Role</h4>

        <button type="button" class="close" data-dismiss="modal">&times;</button>

    </div>
    <div class="modal-body row" style="padding:6%;">

        @using (Html.BeginForm("_Index", "Tickets", FormMethod.Post, htmlAttributes: new { id = "Edit-Ticket-Form" }))
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.TicketId, htmlAttributes: new { @class = "id-resetable" })

            <div class="form">


                <div class="form-group col-md-6 col-sm-12 col-xs-12">



                    @Html.Label("User", htmlAttributes: new { @class = "control-label" })
                    <div class="combobox-auto-select">
                        <input class="input-search" type="text" style="text-transform:capitalize; padding-left:15px; position:absolute; margin:2px; height:30px; background:none; width:80%; color:none; border:none;" />
                        @Html.DropDownList("UserPointDeVenteId", null, "Select User", htmlAttributes: new { @class = "form-control ddl-to-filter dropdown-resetable", id = "ddlUserPointDeVenteId" })
                    </div>
                </div>



            </div>

            <div class="col-md-12 col-sm-12 col-xs-12" style="border-top:1px solid #d7d7d7; padding-top:10px; text-align:right;">

                <button type="submit" class="btn btn-sm btn-info submit"><span class="glyphicon glyphicon-save-file"></span> Save <span class="glyphicon glyphicon-refresh loader" style="display:none;"></span> </button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>

            </div>
        }
    </div>