TchotchoLoto/Models/LivJwetla.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivJwetla
    {
        public int LivJwetlaId { get; set; }
        public bool IsManmanBoulLa { get; set; }
        public int NbreBouleGagner { get; set; }
        public int PrixTicket { get; set; }
        public int MontantAPayer { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    }
}

TchotchoLoto/Controllers/LivJwetLaController.cs
using System;
using TchotchoLoto.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TchotchoLoto.Controllers
{
    public class LivJwetLaController : Controller
    {

        Entities db = new Entities();

        // GET: LivJwetLas


        [AjaxOnly]
        public ActionResult Index()
        {
            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];

            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }



            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "LivJwetLas/Index", "Button Book Player [Books]");


            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }

            if (currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "livjwetla" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {

                ViewBag.LivJwetLa = db.LivJwetlas.OrderBy(l => l.NbreBouleGagner).ToList();
                return View();

            }
            else
            {
                return Json(new { noPermission = true }, JsonRequestBehavior.AllowGet);
            }

        }




        [AjaxOnly]
        public ActionResult __Index()
        {
            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];

            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }


            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }

            if (currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "livjwetla" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {

                ViewBag.LivJwetLa = db.LivJwetlas.OrderBy(l => l.NbreBouleGagner).ToList();
                return PartialView();

            }
            else
            {
                return Json(new { noPermission = true }, JsonRequestBehavior.AllowGet);
            }

        }






        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _Index([Bind(Include = "LivJwetlaId, IsManmanBoulLa, NbreBouleGagner, PrixTicket, MontantAPayer")] LivJwetla livJwetla)
        {
            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];

            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }



            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "LivJwetLas/_Index", "Button Edit or Add Bool Player [Books]");



            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }


            if (currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "livjwetla" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {

                string message = null;

                int livJwetLaExist = db.LivJwetlas.Where(l => l.NbreBouleGagner == livJwetla.NbreBouleGagner && l.IsManmanBoulLa == livJwetla.IsManmanBoulLa && l.PrixTicket == livJwetla.PrixTicket && l.LivJwetlaId != livJwetla.LivJwetlaId).Count();

                if (livJwetLaExist == 0 && (livJwetla.NbreBouleGagner > 0 || (livJwetla.NbreBouleGagner == 0 && livJwetla.IsManmanBoulLa) ) && livJwetla.NbreBouleGagner <= 5 && livJwetla.PrixTicket > 0 && livJwetla.MontantAPayer > 0)
                {
                    try
                    {
                        if (livJwetla.LivJwetlaId != 0)
                        {
                            LivJwetla livJwetlaEdit = db.LivJwetlas.FirstOrDefault(r => r.LivJwetlaId == livJwetla.LivJwetlaId);

                            if (livJwetlaEdit == null)
                            {
                                message = "The Book Player not Found!";
                                return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);
                            }

                            livJwetlaEdit.NbreBouleGagner = livJwetla.NbreBouleGagner;
                            livJwetlaEdit.IsManmanBoulLa = livJwetla.IsManmanBoulLa;
                            livJwetlaEdit.MontantAPayer = livJwetla.MontantAPayer;
                            livJwetlaEdit.PrixTicket = livJwetla.PrixTicket;
                            livJwetlaEdit.ModifiePar = currentUser.FirstName + " " + currentUser.LastName;
                            livJwetlaEdit.ModifieDate = DateTime.Now;
                            db.Entry(livJwetlaEdit).State = EntityState.Modified;

                        }
                        else
                        {

                            livJwetla.ModifiePar = currentUser.FirstName + " " + currentUser.LastName;
                            livJwetla.ModifieDate = DateTime.Now;
                            db.LivJwetlas.Add(livJwetla);

                        }

                        db.SaveChanges();

                        message = "Saved successfully!";
                        return Json(new { saved = true, message }, JsonRequestBehavior.AllowGet);

                    }
                    catch (Exception e)
                    {
                        message = "Operation failed!";
                        return Json(new { dbEx = true, message }, JsonRequestBehavior.AllowGet);

                    }
                }
                else if (livJwetla.NbreBouleGagner <= 0 && !livJwetla.IsManmanBoulLa)
                {
                    message = "Please enter Win Ball quantity!";
                    return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                }
                else if (livJwetla.MontantAPayer <= 0)
                {
                    message = "Please enter the amount to pay!";
                    return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                }
                 else if (livJwetla.PrixTicket <= 0)
                {
                    message = "Please enter the Ticket Price!";
                    return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                }
                 else if (livJwetla.NbreBouleGagner > 5)
                {
                    message = "Quantity of ball won can not excede 5!";
                    return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                }
                else if (livJwetLaExist > 0)
                {
                    message = "Book Player instruction is already exist!";
                    return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    message = "ERROR......!";
                    return Json(new { validationError = true, message }, JsonRequestBehavior.AllowGet);

                }

            }
            else
            {
                return Json(new { noPermission = true }, JsonRequestBehavior.AllowGet);
            }

        }



        [AjaxOnly]
        public ActionResult _Edit(int? id)
        {
            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];

            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }



            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "LivJwetLas/_Edit", "Button Edit [Books]");


            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }


            if (currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "livjwetla" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "edit")))
            {

                string message = null;
                if (id == null)
                {
                    message = "Id Book Player not Found!";

TchotchoLoto/Views/LivJwetLa/Index.cshtml
@model TchotchoLoto.Models.LivJwetla

@{
    ViewBag.Title = "Book Player";
    Layout = null;
}

<input type="hidden" class="title" data-title="book Player" />

<div class="indicator">
    Book  &nbsp;&nbsp; <span class="glyphicon glyphicon-chevron-right"></span> &nbsp; &nbsp; Book Player

</div>
<div class="header-body">
    <p style="display:inline-block;">
        &nbsp;&nbsp;Book  (<span id="hb-nbre-livJwetLa">
            @if (ViewBag.LivJwetLa != null)
            {@ViewBag.LivJwetLa.Count}
        else { Write(0); }
        </span>)
        &nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon star glyphicon-star text-success"></span>

    </p>

    <div style="display:inline-block;" class="header-buttons">
        <button class="add-after-edit add-after-edit btn btn-success btn-sm pull-right" data-toggle="modal" data-target="#create-livJwetLa-modal">
            <span class="glyphicon glyphicon-plus"></span> Add Book Player
        </button>
    </div>
</div>

<br />

<div class="page-scroll-content" id="livJwetLa-list-pv">

    @Html.Partial("__Index")

</div>

<input id="url-get-livJwetLa-list" type="hidden" data-url="@Url.Action("__Index", "LivJwetLa")" />

<div id="create-livJwetLa-modal" class="modal fade" role"dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <div class="modal-content">
            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Add Book Player</h4>

                <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>
            <div class="modal-body row" style="padding:6%;">

                @using (Html.BeginForm("_Index", "LivJwetLa", FormMethod.Post, htmlAttributes: new { id = "Add-LivJwetLa-Form" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.HiddenFor(model => model.LivJwetlaId, htmlAttributes: new { @class = "id-resetable" })

                <div class="form">

                    <div class="form-group col-md-12 col-sm-12">
                        @Html.LabelFor(model => model.NbreBouleGagner, "Quantity of ball won", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.NbreBouleGagner, new { htmlAttributes = new { @class = "form-control editor-resetable" } })
                    </div>



                    <div class="form-group col-md-12 col-sm-12">

                        <div class="input-group">
                            <div class="input-group-addon">
                                @Html.CheckBox("IsManmanBoulLa", false, htmlAttributes: new { @class = "btn btn-default check-box-resetable" })
                            </div>
                            <div class="form-control">
                                <label class="control-label">Is jacpot</label>
                            </div>
                        </div>


                    </div>


                    <div class="form-group col-md-12 col-sm-12">
                        @Html.LabelFor(model => model.PrixTicket, "Ticket Price", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.PrixTicket, new { htmlAttributes = new { @class = "form-control editor-resetable" } })
                    </div>


                    <div class="form-group col-md-12 col-sm-12">
                        @Html.LabelFor(model => model.MontantAPayer, "Amount to Pay", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.MontantAPayer, new { htmlAttributes = new { @class = "form-control editor-resetable" } })
                    </div>





                </div>

                    <div class="col-md-12 col-sm-12 col-xs-12" style="border-top:1px solid #d7d7d7; padding-top:10px; text-align:right;">

                        <button type="submit" class="btn btn-sm btn-info submit"><span class="glyphicon glyphicon-save-file"></span> Save <span class="glyphicon glyphicon-refresh loader" style="display:none;"></span> </button>
                        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>

                    </div>


                }



            </div>

        </div>
    </div>
</div>



<div id="edit-livJwetLa-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">


    </div>
</div>



<!-- Modal 2 Dialog for delete option -->
<div id="delete-modal" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Delete</h4>

                <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>

            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-alert" style="display:block; font-size: 20px;"></span>
                <h5 class="text-warning" style="display:block;">Do you really want to Delete this Book Player ?</h5>

            </div>

            <div class="modal-footer">

                <a class="delete-confirmed btn btn-sm btn-danger" href="#">
                    YES
                </a>

                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">
                    NO
                </button>

            </div>
        </div>

    </div>
</div>



<a id="validation-link" data-toggle="modal" data-target="#modal-dialog-message"></a>

<div id="modal-dialog-message" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Message</h4>

            </div>
            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-info-sign" style="display:block; font-size: 20px;"></span>
                <h5 class="text-info" style="display:block;">@ViewBag.message</h5>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">
                    OK
                </button>
            </div>
        </div>

    </div>
</div>

<div id="pv-overlay-loading" class="overlay-loading bc-overlay-loading" style="display:none;">
    <img src="~/Content/images/loading-gif.gif" alt="Loading" width="50" height="50" />
</div>

TchotchoLoto/Views/LivJwetLa/_Edit.cshtml
@model TchotchoLoto.Models.LivJwetla

<div class="modal-content">
    <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

        <h4 style="display: inline;">Edit Book Player</h4>

        <button type="button" class="close" data-dismiss="modal">&times;</button>

    </div>
    <div class="modal-body row" style="padding:6%;">

        @using (Html.BeginForm("_Index", "LivJwetLa", FormMethod.Post, htmlAttributes: new { id = "Edit-LivJwetLa-Form" }))
        {
            @Html.AntiForgeryToken()


            @Html.HiddenFor(model => model.LivJwetlaId, htmlAttributes: new { @class = "id-resetable" })

            <div class="form">

                <div class="form-group col-md-12 col-sm-12">
                    @Html.LabelFor(model => model.NbreBouleGagner, "Quantity of ball won", htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.NbreBouleGagner, new { htmlAttributes = new { @class = "form-control editor-resetable" } })
                </div>



                <div class="form-group col-md-12 col-sm-12">

                    <div class="input-group">
                        
                        <div class="input-group-addon">
                            @if (Model != null && Model.IsManmanBoulLa == true)
                            {
                                @Html.CheckBox("IsManmanBoulLa", true, htmlAttributes: new { @class = "btn btn-default  check-box-resetable" })
                            }
                            else
                            {
                                @Html.CheckBox("IsManmanBoulLa", false, htmlAttributes: new { @class = "btn btn-default" })
                            }
                        </div>
                        <div class="form-control">
                            <label class="control-label">Is jacpot</label>
                        </div>
                    </div>



                </div>



                <div class="form-group col-md-12 col-sm-12">
                    @Html.LabelFor(model => model.PrixTicket, "Ticket Price", htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.PrixTicket, new { htmlAttributes = new { @class = "form-control editor-resetable" } })
                </div>



                

                <div class="form-group col-md-12 col-sm-12">
                    @Html.LabelFor(model => model.MontantAPayer, "Amount to Pay", htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.MontantAPayer, new { htmlAttributes = new { @class = "form-control editor-resetable" } })
                </div>





            </div>


            <div class="col-md-12 col-sm-12 col-xs-12" style="border-top:1px solid #d7d7d7; padding-top:10px; text-align:right;">

                <button type="submit" class="btn btn-sm btn-info submit"><span class="glyphicon glyphicon-save-file"></span> Save <span class="glyphicon glyphicon-refresh loader" style="display:none;"></span> </button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>

            </div>

        }

    </div>

</div>

TchotchoLoto/Views/LivJwetLa/__Index.cshtml
@{
    var curUser = (TchotchoLoto.Models.User)Session["userData"];

}

<input type="hidden" id="nbre-livJwetLa" value="@if (ViewBag.LivJwetLa != null) { @ViewBag.LivJwetLa.Count}else{ Write(0); }" />

<div id="pv-overlay-loading" class="overlay-loading" style="display:none;">
    <img src="~/Content/images/loading-gif.gif" alt="Loading" width="50" height="50" />

</div>


<div class="table-responsive">
    <table id="datatable" class="table table-hover display" style="width:100%;">

        <thead class="bg-success">

            <tr>
                <th>
                    Quamtity
                </th>
                <th>
                    Is Jacpot
                </th>
                <th>
                    Ticket Price
                </th>
                <th>
                    Amount to Pay
                </th>
                @if (curUser != null && curUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "livjwetla" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "edit")))
                {
                    <th style="text-align:center;">
                        Action
                    </th>
                }
            </tr>

        </thead>

        <tbody>
            @if (ViewBag.LivJwetLa != null)
            {
                foreach (var item in (List<TchotchoLoto.Models.LivJwetla>)ViewBag.LivJwetLa)
                {
                    <tr>
                        <td>
                            @item.NbreBouleGagner
                        </td>
                        <td>
                            @if (item.IsManmanBoulLa)
                            {
                                <span> Yes</span>}

                            else
                            { <span> No </span>}

                        </td>


                        <td>

                            @item.PrixTicket HTG
                        </td>

                        <td>
                            @item.MontantAPayer HTG
                        </td>

                        @if (curUser != null && curUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "livjwetla" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "edit")))
                        {
                            <td style="text-align:center;">

                                <button data-url="@Url.Action("_Edit", "LivJwetLa", new { id = item.LivJwetlaId })" class="edit-livJwetLa-btn btn btn-xs btn-info"><span class="glyphicon glyphicon-edit"></span> Edit</button>

                            </td>
                        }

                    </tr>
                }
            }
        </tbody>

    </table>
</div>