TchotchoLoto/Models/AddUserActionLog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddUserActionLog
    {
        public int AddUserActionLogId { get; set; }
        public int UserId { get; set; }
        public string Info { get; set; }
        public string Action { get; set; }
        public string ActionDesc { get; set; }
        public System.DateTime DateModif { get; set; }
    }
}

TchotchoLoto/Controllers/AddUserActionLogsController.cs
using System;
using TchotchoLoto.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TchotchoLoto.Controllers
{
    public class AddUserActionLogsController : Controller
    {

        Entities db = new Entities();


        // GET: AddUserActionLogs

        [AjaxOnly]
        public ActionResult Index()
        {
            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];

            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }



            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "AddUserActionLogs/Index", "Button Action histories [Security]");


            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }

            if (currentUser.SuperUser && currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "adduseractionlogs" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {

                ViewBag.ActionHistories = new List<AddUserActionLog>();
                return View();

            }
            else
            {
                return Json(new { noPermission = true }, JsonRequestBehavior.AllowGet);
            }

        }




        [AjaxOnly]
        public ActionResult __Index(DateTime? dateDebut, DateTime? dateFin)
        {
            User currentUser = (User)Session["userData"];
            Compagnie currentCompagnie = (Compagnie)Session["compagnieData"];

            if (currentUser == null || currentCompagnie == null)
            {
                return Json(new { returnToLogin = true }, JsonRequestBehavior.AllowGet);
            }

            new AccountController().AddUserActionLog(currentUser, currentCompagnie, "AddUserActionLogs/__Index", "Button Action histories (Begin and End Date) [Security]");


            int sessionIdExist = db.Users.Where(u => u.SessionId == HttpContext.Session.SessionID).Count();

            if (sessionIdExist == 0)
            {
                HttpContext.Session.Abandon();
                string message1 = "You have lost this connection because a new one has been detected!";
                return Json(new { newSession = true, message1 }, JsonRequestBehavior.AllowGet);

            }

            if (currentUser.SuperUser && currentUser.Role.RolePermissions.ToList().Exists(u => u.Permission.ParentName.Trim().ToLower() == "adduseractionlogs" && (u.FullPermission || u.Permission.ObjectName.Trim().ToLower() == "index")))
            {


                string message = "";
                DateTime today = DateTime.Now;
                if (dateDebut == null)
                {
                    message = "Please Enter the Begin Date!";
                    return Json(new { notFound = true, message }, JsonRequestBehavior.AllowGet);
                }



                if (dateFin == null)
                {
                    message = "Please Enter the End Date!";
                    return Json(new { notFound = true, message }, JsonRequestBehavior.AllowGet);
                }


                if (dateDebut.Value > dateFin.Value)
                {
                    message = "The Begin Date cannot exceed the End Date!";
                    return Json(new { notFound = true, message }, JsonRequestBehavior.AllowGet);
                }


                ViewBag.ActionHistories = db.AddUserActionLogs.Where(l => l.DateModif >= dateDebut && l.DateModif <= dateFin).OrderBy(a => a.AddUserActionLogId).ToList();
                return PartialView();

            }
            else
            {
                return Json(new { noPermission = true }, JsonRequestBehavior.AllowGet);
            }

        }



    }
}

TchotchoLoto/Views/AddUserActionLogs/Index.cshtml
@model TchotchoLoto.Models.AddUserActionLog

@{

    ViewBag.Title = "Action Histories";
    Layout = null;
}

<input type="hidden" class="title" data-title="Action Histories" />

<div class="indicator">
    Security  &nbsp;&nbsp; <span class="glyphicon glyphicon-chevron-right"></span> &nbsp; &nbsp; Action Histories

</div>



<div class="header-body">

    <p style="display:inline-block;" class="qt-dataTable">
        &nbsp;&nbsp;Action Histories (<span id="hb-nbre-actionHistories">
            @if (ViewBag.ActionHistories != null)
            {@ViewBag.ActionHistories.Count}
        else { Write(0); }
        </span>)
        &nbsp;<span class="glyphicon star glyphicon-star text-success"></span>

        @using (Html.BeginForm("__Index", "AddUserActionLogs", FormMethod.Get, htmlAttributes: new { id = "actionHistories-list-form" }))
        {

            <div class="form-group col-md-3 col-sm-4 col-xs-4" title="Begin Date" style="padding-left:1px; width: 200px;">
                <input type="datetime-local" name="dateDebut" id="dateDebut" class="form-control date-picker-resetable" style="border: 1px solid #31b0d5; background: #31b0d5; color:white;">
            </div>

            <div class="form-group col-md-3 col-sm-4 col-xs-4" title="End Date" style="margin-left:-25px; width: 200px;">
                <input type="datetime-local" name="dateFin" id="dateFin" class="form-control date-picker-resetable" style="border: 1px solid #31b0d5; background: #31b0d5; color:white;">
            </div>
            <div class="form-group col-md-2 col-sm-2 col-xs-2" style="margin-left:-25px;">
                <button style="margin-right:10px; background: #31b0d5; color: dimgrey; border: none; color:white;" class="btn btn-md  submit" title="Search for this Date">
                    <span class="glyphicon glyphicon-search"></span>
                </button>


            </div>
        }


        <button data-url="@Url.Action("SendAllActionUserParDateParEmail", "Emails")" class="envoie-email-rapport-par-date-btn btn btn-sm btn-primary" title="Send report by E-mail">
            <span class="glyphicon glyphicon-send"></span> &nbsp;<span class="glyphicon glyphicon-envelope"></span>
        </button>
    </p>


    <div style="display:inline-block;" class="header-buttons">
        <button style="margin-right: 10px;" data-url="@Url.Action("SendAllActionUserParEmail", "Emails")" class="send-current-rapport-btn btn btn-sm btn-primary">  <span class="glyphicon glyphicon-send"></span> <span> Send Action Users by E-mail</span> <span class="glyphicon glyphicon-envelope"> </span> </button>
    </div>



</div>

<br />



<div class="page-scroll-content" id="actionHistories-list-pv">

    @Html.Partial("__Index")

</div>





<a id="validation-link" data-toggle="modal" data-target="#modal-dialog-message"></a>

<div id="modal-dialog-message" class="modal fade" app-navigation="dialog" data-backdrop="static">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #0078d7; border-radius:5px 5px 0 0;">

                <h4 style="display: inline;">Message</h4>

            </div>
            <div class="modal-body row" style="padding:7%; text-align:center;">

                <span class="glyphicon glyphicon-info-sign" style="display:block; font-size: 20px;"></span>
                <h5 class="text-info" style="display:block;">@ViewBag.message</h5>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">
                    OK
                </button>
            </div>
        </div>

    </div>
</div>

<div id="pv-overlay-loading" class="overlay-loading bc-overlay-loading" style="display:none;">
    <img src="~/Content/images/loading-gif.gif" alt="Loading" width="50" height="50" />
</div>

TchotchoLoto/Views/AddUserActionLogs/__Index.cshtml
<input type="hidden" id="nbre-actionHistories" value="@if (ViewBag.ActionHistories != null) { @ViewBag.ActionHistories.Count}else{ Write(0); }" />

<div id="pv-overlay-loading" class="overlay-loading" style="display:none;">
    <img src="~/Content/images/loading-gif.gif" alt="Loading" width="50" height="50" />
</div>


<div class="table-responsive">
    <table id="datatable" class="table table-hover display" style="width:100%;">

        <thead class="bg-success">

            <tr>
                <th>
                    No
                </th>
                
                <th>
                    User Infos
                </th>
                <th>
                    Action
                </th>
                <th>
                    Action Description
                </th>
                <th>
                    Action Date
                </th>

            </tr>

        </thead>

        <tbody class="big-table-height">
            @if (ViewBag.ActionHistories != null)
            {
                int i = 1;

                foreach (var item in (List<TchotchoLoto.Models.AddUserActionLog>)ViewBag.ActionHistories)
                {
                    <tr>
                        <td>
                            @i )
                        </td>
                        @*<td>
                            @item.UserId
                        </td>*@
                        
                        <td>
                            @item.Info
                        </td>
                        <td>
                            @item.Action
                        </td>
                        <td>
                            @item.ActionDesc
                        </td>
                        <td>
                            @item.DateModif
                        </td>

                    </tr>

                    i++;
                }
            }
        </tbody>

    </table>
</div>